//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 10:59:06 AM CDT 
//

@XmlSchema(
namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero",
elementFormDefault = XmlNsForm.QUALIFIED,
xmlns={@XmlNs(prefix="tpe", namespaceURI="http://www.sat.gob.mx/TuristaPasajeroExtranjero")})  

package mx.xpd.cfdi.domain.cfdi.complementos.turistapasajeroextranjero;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;


