package mx.xpd.cfdi.domain.cfdi.complementos.registroFiscal;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.05.18 at 04:48:25 PM CDT 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.0" />
*       &lt;attribute name="Folio" use="required">
*         &lt;simpleType>
*           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
*             &lt;pattern value="[0-9]{16}"/>
*           &lt;/restriction>
*         &lt;/simpleType>
*       &lt;/attribute>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlRootElement(name = "CFDIRegistroFiscal")
public class CFDIRegistroFiscal {

 protected String version;
 protected String folio;

 /**
  * Gets the value of the version property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 @XmlAttribute(name = "Version")
 public String getVersion() {
     if (version == null) {
         return "1.0";
     } else {
         return version;
     }
 }

 /**
  * Sets the value of the version property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setVersion(String value) {
     this.version = value;
 }

 /**
  * Gets the value of the folio property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 @XmlAttribute(name = "Folio")
 public String getFolio() {
     return folio;
 }

 /**
  * Sets the value of the folio property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setFolio(String value) {
     this.folio = value;
 }

}
