//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 11:32:19 PM CST 
//

@XmlSchema(
namespace = "http://www.sat.gob.mx/detallista", 
elementFormDefault = XmlNsForm.QUALIFIED,
xmlns={@XmlNs(prefix="detallista", namespaceURI="http://www.sat.gob.mx/detallista")})  

package mx.xpd.cfdi.domain.cfdi.complementos.detallista;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;

